### ISSUE TITLE
How to use widget ?

### ISSUE THREAD

**Issue by pylover** [toscawidgets/tw2.recaptcha#1]
File "/home/vahid/pythonenv/tg232/lib/python2.7/site-packages/tw2/recaptcha/validator.py", line 39, in validate_python
challenge = field_dict['recaptcha_challenge_field']
TypeError: string indices must be integers

**Comment by percious** [comment]
Do you think you could post this to: https://groups.google.com/forum/#!forum/toscawidgets-discuss  I am not sure I can get to it immediately.
Thanks,
-chris

**Comment by pylover** [comment]
Dear chris

Thanks a lot.

I already found a solution, so i will fork the repo, and create 
instruction in readme, and request a pull.
